# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi

# User specific aliases and functions
alias rm='rm -i'
alias mv='mv -i'
alias cp='cp -i'

export LANG=ja_JP.UTF-8

#ヒストリー共有の設定
function share_history {
    history -a
    history -c
    history -r
}
export PROMPT_COMMAND='share_history'
shopt -u histappend
export HISTSIZE=9999

#端末ロックをしない設定
stty stop undef

export EDITOR='vim'

if [ ! -d ~/.ssh ];then
	mkdir ~/.ssh
	chmod 700 ~/.ssh
fi

if [ ! -f ~/.ssh/authorized_keys ];then
	touch ~/.ssh/authorized_keys
	chmod 600 ~/.ssh/authorized_keys
fi

source ~/.bash_colors
PS1="${BBlue}\u${BWhite}@${BPurple}\h${BWhite}:${BBlue}\w${White}\n$ "